### ISSUE TITLE
Python 3.11 problem

### ISSUE THREAD

**Issue by aekoroglu** [Suor/whatever#10]
Testing stage is failing in 3.11

platform linux -- Python 3.11.0rc1, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/aekoroglu/rpmbuild/BUILD/whatever-0.6/.hypothesis/examples')
rootdir: /home/aekoroglu/rpmbuild/BUILD/whatever-0.6
plugins: cov-3.0.0, mock-3.8.2, datadir-1.3.1, hypothesis-6.45.0
collected 0 items / 1 error                                                                                                                                                                                                     

==== ERRORS ====
____ ERROR collecting test_whatever.py ____
test_whatever.py:2: in <module>
    from whatever import _, that
whatever.py:22: in <module>
    class Whatever(object):
whatever.py:30: in Whatever
    __code__ = CodeType(*((1, 1) if PY2 else (1, 0, 0, 1) if PY38 else (1, 0, 1))
E   TypeError: code expected at least 16 arguments, got 14

**Comment by Suor** [comment]
That line needs to be updated.

**Comment by mgorny** [comment]
Ping. This is blocking `funcy` which is blocking further packages.

**Comment by Suor** [comment]
Released in whatever 0.7

**Comment by mgorny** [comment]
Thanks!
