### ISSUE TITLE
Can not map element in numpy array?

### ISSUE THREAD

**Issue by zhiruiwang** [Suor/whatever#6]
from cytoolz import pipe
from cytoolz.curried import map
from whatever import _
pipe(range(5),np.array,map(_**2),list)
Out[96]: 
[NotImplemented,
 NotImplemented,
 NotImplemented,
 NotImplemented,
 NotImplemented]

pipe(range(5),np.array,map(lambda x:x**2),list)
Out[97]: [0, 1, 4, 9, 16]

It seems like the '_' operator can not be implemented on numpy array?

**Comment by Suor** [comment]
```python
In [5]: map(_**2,np.array(range(5)))
Out[5]: [0, 1, 4, 9, 16]
```
So it's `cytools.curried.map()`.

**Comment by Suor** [comment]
Maybe type is converted somewhere and then `whatever` fails on late binding, see README. You can try `_ ** 2.0`.
